<?php
return array(
    'df_pay' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=df_pay',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'md_bbs' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=md_bbs',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'md_blog' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=md_blog',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_jdrc' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.241,1445;Database=jdrc',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_lms' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=lms',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_meadin' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=meadin',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_cp' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=cp',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_papers' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=papers',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_veryeast' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=veryeast',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_veryeast_cms' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=veryeastcms',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_xzhome' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=XZHome',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_sendmail' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=sendmail',
        'username' => 'superman',
        'password' => 'superman',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'mssql_xzcms' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=xianzhicms',
        'username' => 'superman',
        'password' => 'superman',
    ),
    'mssql_xzbbs' => array(
        'dsn' => 'sqlsrv:Server=10.10.29.123,1445;Database=xzbbs',
        'username' => 'superman',
        'password' => 'superman',
    ),
    'xz_open_course' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=xz_open_course',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_user' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=ve_user',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_company' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_company',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_core' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_core',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_person' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_person',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_stat' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_stat',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_main' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_main',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_college' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_college',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'df_cms' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=df_cms',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => 'md_',
    ),
    'df_resource' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=df_resource',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_notify' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=ve_notify',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    've_mobile' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=veryeast_mobile',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => '',
    ),
    'lms_v2' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=lms_v2',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => 'lms_',
    ),
    'df_mixed' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=df_mixed',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => false,//true,
        'charset' => 'utf8',
    ),
    'xz_v2' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=xz_v2',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => 'xz_',
    ),
    'wams' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=weixin_activities',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => 'wams_',
    ),
    'xz_paper' => array(
        'dsn' => 'mysql:host=10.10.29.238;dbname=xz_papers',
        'username' => 'test',
        'password' => 'test',
        'enableSchemaCache' => true,
        'charset' => 'utf8',
        'tablePrefix' => 'paper_',
    ),
);
